-- WP_** definitions

WP_NONE 			= 0
WP_STUN_BATON 		= 1
WP_MELEE 			= 2
WP_SABER 			= 3
WP_BRYAR_PISTOL 	= 4
WP_BLASTER			= 5
WP_DISRUPTOR		= 6
WP_BOWCASTER		= 7
WP_REPEATER			= 8
WP_DEMP2			= 9
WP_FLECHETTE		= 10
WP_ROCKET_LAUNCHER	= 11
WP_THERMAL			= 12
WP_TRIP_MINE		= 13
WP_DET_PACK			= 14
WP_CONCUSSION		= 15
WP_BRYAR_OLD		= 16
WP_EMPLACED_GUN		= 17
WP_TURRET			= 18
WP_NUM_WEAPONS		= 19

-- AMMO_** definitions

AMMO_NONE			= 0
AMMO_FORCE			= 1
AMMO_BLASTER		= 2
AMMO_POWERCELL		= 3
AMMO_METAL_BOLTS	= 4
AMMO_ROCKETS		= 5
AMMO_EMPLACED		= 6
AMMO_THERMAL		= 7
AMMO_TRIPMINE		= 8
AMMO_DETPACK		= 9
AMMO_MAX			= 10